import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { SignedIn, SignedOut, SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });


  const user = useUser()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
        <div>
          {
            !!user && <p>{user.user?.fullName}</p>
          }
        </div>
      </main>
    </>
  );
}
